---
language: perl

perl:
  - "5.14"
  - "5.24"

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libssl-dev libidn11-dev libexpat1-dev
install: "cpanm -n Module::Install inc::Module::Install && cpanm --installdeps --notest --with-recommends ."
script: "prove -Ilib t/"
