---
language: perl

perl:
  - "5.14"
  - "5.24"

services:
  - docker

install: cpanm -n App::cpm; cpm install -g Module::Install inc::Module::Install; for MOD in Whatbot*/; do echo $MOD; cd $MOD; PERL5LIB=../Whatbot/lib perl Makefile.PL; mymeta-cpanfile > cpanfile; cpm install -g --cpanfile=cpanfile; cd ..; done
script: "export PERL5LIB=$(find `pwd` -name lib | tr '\n' ':').; for MOD in Whatbot*/; do echo $MOD; cd $MOD; perl -Ilib Makefile.PL && make && cpanm --notest .; cd ..; done; prove $(find `pwd` -name t | tr '\n' ' ')"
