name: whatbot

on:
  push:
    branches:
      - main
      - actions-docker
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - 'latest'
          - '5.40'
          - '5.16'
    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v4
      - name: perl -V
        run: perl -V
      - name: Install OS dependencies
        run: apt-get update && apt-get install -y libssl-dev libidn11* libexpat1-dev libreadline-dev
      - name: Install Perl Dependencies
        run: "cpanm -n -q --metacpan Module::Install inc::Module::Install && cpanm --metacpan --installdeps --notest --with-recommends ."
      - name: Run Tests
        run: prove -Ilib t/
  deploy_latest:
    if: github.repository == 'nmelnick/whatbot' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/actions-docker')
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: "nmelnick/whatbot:${{ startsWith(github.ref, 'refs/tags/') && steps.get_version.outputs.VERSION || 'latest' }}"
          file: Dockerfile.deploy
