name: linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.14'
          - '5.24'
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v1
      - name: perl -V
        run: perl -V
      - name: Install OS dependencies
        run: apt-get update && apt-get install -y libssl-dev libidn11* libexpat1-dev
      - name: Install Perl Dependencies
        run: "cpanm -n Module::Install inc::Module::Install && cpanm --installdeps --notest --with-recommends ."
      - name: Run Tests
        run: prove -Ilib t/
